---
    - name: Check if nginx is installed
      block:
        - name: List installed packages
          package_facts:
            manager: auto
        - name: Set fact for nginx installation
          set_fact:
            nginx_installed: "{{ packages['nginx'] is defined }}"
        - name: Show the nginx_installed variable
          debug: var=nginx_installed

    - name: Install nginx
      when: not nginx_installed
      block:
#        - name: Install epel repository
#          yum: name=epel-release state=installed
#          when: ansible_os_family == "RedHat"
        - name: Install nginx
          package: name=nginx state=installed
    
    - name: Disable ipv6 port bind directive in /etc/nginx/nginx.conf 
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^([^#]*listen.*\\[::\\]:[0-9]{1,5}.*)$"
        value: "#\\1"
        backrefs: yes
        backup: yes

    - name: Create /etc/nginx/conf.d/ if not exists
      file: path=/etc/nginx/conf.d/ state=directory
 
    - name: Deploy extra conf for the TLS server
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/tls-server.conf
        force: yes

    - name: Test nginx config
      shell: nginx -t
    
    - name: Add tls_server_host_ip to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ tls_server_host_ip }} {{ tls_server_host }}"
        state: present
      when: tls_server_host_ip is defined

    - name: Start nginx 
      systemd: name=nginx state=restarted 
   
    - name: Verify the SSL connection can be established with the SSL
      uri: 
        url: "https://{{ tls_server_host }}:{{ tls_server_port }}" 
        status_code: 200
        return_content: yes
        timeout: 120
      environment:
        no_proxy: "{{ tls_server_host }},{{ lookup('env', 'no_roxy') }},localhost"

    - name: Clean up
      block:
        - name: Delete TLS config
          file: path=/etc/nginx/conf.d/tls-server.conf state=absent
        - name: Uninstall nginx
          package: name=nginx state=absent
          when: not nginx_installed
        - name: Delete /etc/nginx
          file: path=/etc/nginx state=absent
          when: not nginx_installed
